---
PROD:
  PASSWORD_PATH: ""
  PASSWORD_FOLDER: ""

WARRANTY:
  PASSWORD_PATH: ""
  PASSWORD_FOLDER: ""

TESTING:
  PASSWORD_PATH: ""
  PASSWORD_FOLDER: ""
  LINK: "" 
  PLAYLIST: ""
  ERROR_FILE: ""
  AUDIO_CONVERT: "Downloads/test.mp4"